In [2]:
import  numpy as np

In [12]:
revenue = np.array([[180,90,20,40],[578,23,63,568],[135,364,568,42]])
cost = np.array([1000,2000,300])

expenses = np.array([[324,45,685,96],[457,74,22,346],[25,64,355,4]])

In [4]:
print(expenses)

[[324  45 685  96]
 [457  74  22 346]
 [ 25  64 355   4]]


In [5]:
revenue - expenses

array([[-144,   45, -665,  -56],
       [ 121,  -51,   41,  222],
       [ 110,  300,  213,   38]])

In [13]:
np.dot(cost,revenue)

array([1376500,  245200,  316400, 1188600])